controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_footprint
    odom_frame_id: odom             # Bắt buộc khai báo
    enable_odom_tf: true            # Ép controller phát TF từ odom -> base_footprint
    open_loop: false
    velocity_rolling_window_size: 10

    left_wheel_names: ['left_wheel_to_base_link']
    right_wheel_names: ['right_wheel_to_base_link']
    wheel_separation: 0.435
    wheel_radius: 0.10795
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0

    use_stamped_vel: false

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false