scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        # Góc được tính bằng Radian. 180 độ phía trước tương ứng từ -90° đến +90°
        upper_angle: 1.5708  # -90 độ (Mạn phải)
        lower_angle: -1.5708   # +90 độ (Mạn trái)